Feature solid
Graciano1997/school_library pull request #5
Opened 2023-10-17 10:19 UTC by Graciano1997

In this milestone : @albertkantwi , @Graciano1997  and @wacoo  did:

Refactored the code respecting the following items:

- YAGNI, KISS, and DRY rules and Ruby style guide.
- SOLID principles.
- Ensured the "Single-responsibility Principle".
- Ensured that main.rb asks the user for the initial choice of options (or to quit).
- Extracted some pieces of logic into separate class(es).
Fix linter issues
Update readme

2023-10-17 11:00 UTC, AbelG101 requested changes
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzFmY2U0ZTkwMmM3ZTM5MDBkNjhhZjk0MjI0OTU3MGNjYjMyMmRhOCZjdD1n/M1fddM48g9084bJMEX/giphy.gif)


# Hi @Graciano1997, @wacoo & @albertkantwi 👋, 

You're doing a good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Codebase is modularized ✔
- UI is looking amazing ✔
- Correct use of Git Flow ✔
- Linter check is passing ✔
- Descriptive PR title with a great summary ✔

## Required Changes ♻️
- _Check the comments under the review._
- you just have to make a few changes and you're on your way 🚀.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-17 11:00 UTC, AbelG101 commented on app.rb
https://github.com/Graciano1997/school_library/blob/5607132b0484c6ae6df7a31c6061100486f2239f/app.rb#L60-L93
- [ ] You've done an amazing job refactoring your code so far, but I'd like to give you some suggestions to improve your codebase further. According to the Single responsibility rule, I'd suggest you handle all requests for input and input validation on separate classes/methods whose responsibilities are to request or validate input, which is a clear separation of concerns. Instead of having the logic for creating a student and a teacher in a single method `create_person` I'd suggest you make separate methods `create_teacher` and `create_student` and make sure the code at lines `72` & `86` for initializing a student & a teacher class are placed in the `create_person()` method and not in the separate methods.
  - KISS (Keep It Simple, Stupid):
    - [ ] The code could be simplified by extracting the input prompt and value assignment logic into separate methods. This would improve code modularity and readability. Instead of using if and elsif statements, a case statement can be used to handle different person types.
  - DRY (Don't Repeat Yourself):
    - [ ] The code contains a duplicated input prompt and value assignment logic for name and age. Consider extracting this logic into a separate method to avoid repetition.

- Please refer to the Best Practices and Solid lesson found [here](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid)

2023-10-17 11:00 UTC, AbelG101 commented on app.rb
- [ ] Since similar patterns exist for the `create_book` & `create_rental` methods in your codebase kindly make sure to refactor them considering the above comment.

2023-10-17 17:09 UTC, shahadat3669 requested changes
Hi @Graciano1997, @wacoo, @albertkantwi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media2.giphy.com/media/m3864rBwwBTKMAbpn3/giphy.gif"/>

## Don't Worry 🙏

It's okay to have bugs in your code. 🆗 Please see this code review as an opportunity to learn practical coding skills and discover new tips that can improve your code quality 💯 and help you **get even better** 💼.

**I will guide you on how to address these areas down below 👇.**

## Highlights
✅ No linter Errors
✅ the role of main.rb is only to start their code 
✅ extracted some pieces of logic into a separate class(es)

 ## Required Changes ♻️
👍 I appreciate your efforts in working on your project. However, there are a few important points to address:

1. First, I noticed that you made updates to your project while I was reviewing it. It's generally better to finalize your work before requesting a review. This will help ensure a more accurate review of your project.

2. You've made changes to `people_controller.rb` and `validateperson.rb` based on feedback from the previous reviewer. It's a good practice to incorporate these changes into your code, or at least ensure they are utilized and functional. Currently, when I ran your code in the terminal, it seemed that these files were not being used. Please make sure to implement the changes as suggested by the previous reviewer.

3. Additionally, if you have any files or lines of code that are not necessary or currently unused in your application, consider removing them. Unnecessary files can make your codebase larger and more complex than it needs to be. Streamlining your codebase will lead to a cleaner and more efficient project.

Thank you for your dedication to improving your project, and I encourage you to continue making the necessary updates. Keep up the good work! 👏🚀📝

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table  width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        <img src="https://img.shields.io/badge/github-%23121011.svg?style=for-the-badge&logo=github&logoColor=white" alt="GitHub">
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        <img src="https://img.shields.io/badge/linkedin-%230077B5.svg?style=for-the-badge&logo=linkedin&logoColor=white" alt="LinkedIn">
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        <img src="https://img.shields.io/badge/Slack-4A154B?style=for-the-badge&logo=slack&logoColor=white" alt="Slack">
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        <img src="https://img.shields.io/badge/Gmail-D14836?style=for-the-badge&logo=gmail&logoColor=white" alt="Email">
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-18 08:56 UTC, MahmoudBakr23 approved these changes
Hello TEAM😃, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

**Highlights**
- Well done on implementing the refactoring changes from the previous reviewers. This milestone is complete

Cheers, and Happy coding!👏👏👏

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-18 09:00 UTC, Graciano1997 commented
@MahmoudBakr23  thanks

2023-10-18 09:00 UTC, merged